"""empty message

Revision ID: 2c5726103b47
Revises: 51722d101ce6
Create Date: 2022-08-02 14:18:51.442325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5726103b47'
down_revision = '51722d101ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_to_do_task'), 'to_do', ['task'], unique=True)
    op.create_index(op.f('ix_to_do_timestamp'), 'to_do', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_to_do_timestamp'), table_name='to_do')
    op.drop_index(op.f('ix_to_do_task'), table_name='to_do')
    op.drop_table('to_do')
    # ### end Alembic commands ###
