"""list items

Revision ID: acc7bd194a28
Revises: caeeb743ae60
Create Date: 2022-07-26 14:31:49.984424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc7bd194a28'
down_revision = 'caeeb743ae60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_to_do_timestamp'), 'to_do', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_to_do_timestamp'), table_name='to_do')
    op.drop_column('to_do', 'timestamp')
    # ### end Alembic commands ###
