"""list items

Revision ID: d8e480ac4fcb
Revises: c9cd714670ac
Create Date: 2022-07-25 18:58:09.925023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e480ac4fcb'
down_revision = 'c9cd714670ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_to_do_list_task'), 'to_do_list', ['task'], unique=True)
    op.drop_index('ix_list_item_task', table_name='list_item')
    op.drop_table('list_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_list_item_task', 'list_item', ['task'], unique=False)
    op.drop_index(op.f('ix_to_do_list_task'), table_name='to_do_list')
    op.drop_table('to_do_list')
    # ### end Alembic commands ###
